using System;
using System.Collections.Generic;
using System.Net.Sockets;
using UnityEngine;
using UnityEditor;
using UnityEngine.Serialization;
//


public class Env : MonoBehaviour
{
    public GameObject _HumanoidModel;
    public GameObject Ref;
    public GameObject Spine;
    public GameObject Neck;
    public GameObject Head;
    public GameObject LeftShoulder;
    public GameObject LeftArm;
    public GameObject LeftForeArm;
    public GameObject LeftHand;
    public GameObject RightShoulder;
    public GameObject RightArm;
    public GameObject RightForeArm;
    public GameObject RightHand;
    public GameObject Hips;
    public GameObject LeftUpLeg;
    public GameObject LeftLeg;
    public GameObject LeftAnkle;
    public GameObject LeftToe;
    public GameObject RightUpLeg;
    public GameObject RightLeg;
    public GameObject RightAnkle;
    public GameObject RightToe;


    //Rigidbody RefRB;
    Rigidbody RefRB;
    Rigidbody SpineRB;
    Rigidbody NeckRB;
    Rigidbody HeadRB;
    Rigidbody LeftShoulderRB;
    Rigidbody LeftArmRB;
    Rigidbody LeftForeArmRB;
    Rigidbody LeftHandRB;
    Rigidbody RightShoulderRB;
    Rigidbody RightArmRB;
    Rigidbody RightForeArmRB;
    Rigidbody RightHandRB;
    Rigidbody HipsRB;
    Rigidbody LeftUpLegRB;
    Rigidbody LeftLegRB;
    Rigidbody LeftAnkleRB;
    Rigidbody LeftToeRB;
    Rigidbody RightUpLegRB;
    Rigidbody RightLegRB;
    Rigidbody RightAnkleRB;
    Rigidbody RightToeRB;

    public GameObject Floor;
    Rigidbody FloorRB;

    float Ref_x;
    float Spine_x;
    float Neck_x;
    float Head_x;
    float LeftShoulder_x;
    float LeftArm_x;
    float LeftForeArm_x;
    float LeftHand_x;
    float RightShoulder_x;
    float RightArm_x;
    float RightForeArm_x;
    float RightHand_x;
    float Hips_x;
    float LeftUpLeg_x;
    float LeftLeg_x;
    float LeftAnkle_x;
    float LeftToe_x;
    float RightUpLeg_x;
    float RightLeg_x;
    float RightAnkle_x;
    float RightToe_x;
    float Ref_rx;
    float Spine_rx;
    float Neck_rx;
    float Head_rx;
    float LeftShoulder_rx;
    float LeftArm_rx;
    float LeftForeArm_rx;
    float LeftHand_rx;
    float RightShoulder_rx;
    float RightArm_rx;
    float RightForeArm_rx;
    float RightHand_rx;
    float Hips_rx;
    float LeftUpLeg_rx;
    float LeftLeg_rx;
    float LeftAnkle_rx;
    float LeftToe_rx;
    float RightUpLeg_rx;
    float RightLeg_rx;
    float RightAnkle_rx;
    float RightToe_rx;
    float Ref_y;
    float Spine_y;
    float Neck_y;
    float Head_y;
    float LeftShoulder_y;
    float LeftArm_y;
    float LeftForeArm_y;
    float LeftHand_y;
    float RightShoulder_y;
    float RightArm_y;
    float RightForeArm_y;
    float RightHand_y;
    float Hips_y;
    float LeftUpLeg_y;
    float LeftLeg_y;
    float LeftAnkle_y;
    float LeftToe_y;
    float RightUpLeg_y;
    float RightLeg_y;
    float RightAnkle_y;
    float RightToe_y;
    float Ref_ry;
    float Spine_ry;
    float Neck_ry;
    float Head_ry;
    float LeftShoulder_ry;
    float LeftArm_ry;
    float LeftForeArm_ry;
    float LeftHand_ry;
    float RightShoulder_ry;
    float RightArm_ry;
    float RightForeArm_ry;
    float RightHand_ry;
    float Hips_ry;
    float LeftUpLeg_ry;
    float LeftLeg_ry;
    float LeftAnkle_ry;
    float LeftToe_ry;
    float RightUpLeg_ry;
    float RightLeg_ry;
    float RightAnkle_ry;
    float RightToe_ry;
    float Ref_z;
    float Spine_z;
    float Neck_z;
    float Head_z;
    float LeftShoulder_z;
    float LeftArm_z;
    float LeftForeArm_z;
    float LeftHand_z;
    float RightShoulder_z;
    float RightArm_z;
    float RightForeArm_z;
    float RightHand_z;
    float Hips_z;
    float LeftUpLeg_z;
    float LeftLeg_z;
    float LeftAnkle_z;
    float LeftToe_z;
    float RightUpLeg_z;
    float RightLeg_z;
    float RightAnkle_z;
    float RightToe_z;
    float Ref_rz;
    float Spine_rz;
    float Neck_rz;
    float Head_rz;
    float LeftShoulder_rz;
    float LeftArm_rz;
    float LeftForeArm_rz;
    float LeftHand_rz;
    float RightShoulder_rz;
    float RightArm_rz;
    float RightForeArm_rz;
    float RightHand_rz;
    float Hips_rz;
    float LeftUpLeg_rz;
    float LeftLeg_rz;
    float LeftAnkle_rz;
    float LeftToe_rz;
    float RightUpLeg_rz;
    float RightLeg_rz;
    float RightAnkle_rz;
    float RightToe_rz;
    float RefRB_x;
    float SpineRB_x;
    float NeckRB_x;
    float HeadRB_x;
    float LeftShoulderRB_x;
    float LeftArmRB_x;
    float LeftForeArmRB_x;
    float LeftHandRB_x;
    float RightShoulderRB_x;
    float RightArmRB_x;
    float RightForeArmRB_x;
    float RightHandRB_x;
    float HipsRB_x;
    float LeftUpLegRB_x;
    float LeftLegRB_x;
    float LeftAnkleRB_x;
    float LeftToeRB_x;
    float RightUpLegRB_x;
    float RightLegRB_x;
    float RightAnkleRB_x;
    float RightToeRB_x;
    float RefRB_rx;
    float SpineRB_rx;
    float NeckRB_rx;
    float HeadRB_rx;
    float LeftShoulderRB_rx;
    float LeftArmRB_rx;
    float LeftForeArmRB_rx;
    float LeftHandRB_rx;
    float RightShoulderRB_rx;
    float RightArmRB_rx;
    float RightForeArmRB_rx;
    float RightHandRB_rx;
    float HipsRB_rx;
    float LeftUpLegRB_rx;
    float LeftLegRB_rx;
    float LeftAnkleRB_rx;
    float LeftToeRB_rx;
    float RightUpLegRB_rx;
    float RightLegRB_rx;
    float RightAnkleRB_rx;
    float RightToeRB_rx;
    float RefRB_y;
    float SpineRB_y;
    float NeckRB_y;
    float HeadRB_y;
    float LeftShoulderRB_y;
    float LeftArmRB_y;
    float LeftForeArmRB_y;
    float LeftHandRB_y;
    float RightShoulderRB_y;
    float RightArmRB_y;
    float RightForeArmRB_y;
    float RightHandRB_y;
    float HipsRB_y;
    float LeftUpLegRB_y;
    float LeftLegRB_y;
    float LeftAnkleRB_y;
    float LeftToeRB_y;
    float RightUpLegRB_y;
    float RightLegRB_y;
    float RightAnkleRB_y;
    float RightToeRB_y;
    float RefRB_ry;
    float SpineRB_ry;
    float NeckRB_ry;
    float HeadRB_ry;
    float LeftShoulderRB_ry;
    float LeftArmRB_ry;
    float LeftForeArmRB_ry;
    float LeftHandRB_ry;
    float RightShoulderRB_ry;
    float RightArmRB_ry;
    float RightForeArmRB_ry;
    float RightHandRB_ry;
    float HipsRB_ry;
    float LeftUpLegRB_ry;
    float LeftLegRB_ry;
    float LeftAnkleRB_ry;
    float LeftToeRB_ry;
    float RightUpLegRB_ry;
    float RightLegRB_ry;
    float RightAnkleRB_ry;
    float RightToeRB_ry;
    float RefRB_z;
    float SpineRB_z;
    float NeckRB_z;
    float HeadRB_z;
    float LeftShoulderRB_z;
    float LeftArmRB_z;
    float LeftForeArmRB_z;
    float LeftHandRB_z;
    float RightShoulderRB_z;
    float RightArmRB_z;
    float RightForeArmRB_z;
    float RightHandRB_z;
    float HipsRB_z;
    float LeftUpLegRB_z;
    float LeftLegRB_z;
    float LeftAnkleRB_z;
    float LeftToeRB_z;
    float RightUpLegRB_z;
    float RightLegRB_z;
    float RightAnkleRB_z;
    float RightToeRB_z;
    float RefRB_rz;
    float SpineRB_rz;
    float NeckRB_rz;
    float HeadRB_rz;
    float LeftShoulderRB_rz;
    float LeftArmRB_rz;
    float LeftForeArmRB_rz;
    float LeftHandRB_rz;
    float RightShoulderRB_rz;
    float RightArmRB_rz;
    float RightForeArmRB_rz;
    float RightHandRB_rz;
    float HipsRB_rz;
    float LeftUpLegRB_rz;
    float LeftLegRB_rz;
    float LeftAnkleRB_rz;
    float LeftToeRB_rz;
    float RightUpLegRB_rz;
    float RightLegRB_rz;
    float RightAnkleRB_rz;
    float RightToeRB_rz;
    float Reward;
    float done;
    float Step;
    private bool initial_flag;
    public bool stop_flag;
    private int i;

    float multiplier;
    float countdown;
    float target;

    float[] data_Out = new float[254];
    float[] vectorAction = new float[11];
    float[] initStates = new float[254];

    public string ip = "127.0.0.1";
    public int port = 60000;
    private Socket client;
    [SerializeField]
    private float[] dataOut, dataIn;
    protected float[] ServerRequest(float[] dataOut)
    {
        this.dataOut = dataOut;
        this.dataIn = SendAndReceive(dataOut);
        return this.dataIn;
    }

    private float[] SendAndReceive(float[] dataOut)
    {
        //initialize socket
        float[] floatsReceived;
        client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        client.Connect(ip, port);
        if (!client.Connected) {
            Debug.LogError("Connection Failed");
            return null;
        }

        //convert floats to bytes, send to port
        var byteArray = new byte[dataOut.Length * 4];
        Buffer.BlockCopy(dataOut, 0, byteArray, 0, byteArray.Length);
        client.Send(byteArray);

        //allocate and receive bytes
        byte[] bytes = new byte[4000];
        int idxUsedBytes = client.Receive(bytes);
        //print(idxUsedBytes + " new bytes received.");

        //convert bytes to floats
        floatsReceived = new float[idxUsedBytes/4];
        Buffer.BlockCopy(bytes, 0, floatsReceived, 0, idxUsedBytes);

        client.Close();
        return floatsReceived;
    }

    void Start () 
    {
        Ref = 
            _HumanoidModel.transform.Find( "Root" ).gameObject;
        Spine = 
            Ref.transform.Find( "Ribs" ).gameObject;
        Neck = 
            Spine.transform.Find( "Neck" ).gameObject;
        Head = 
            Neck.transform.Find( "Head" ).gameObject;
        LeftShoulder = 
            Spine.transform.Find( "Left_Shoulder_Joint_01" ).gameObject;
        LeftArm = 
            LeftShoulder.transform.Find( "Left_Upper_Arm_Joint_01" ).gameObject;
        LeftForeArm = 
            LeftArm.transform.Find( "Left_Forearm_Joint_01" ).gameObject;
        LeftHand = 
            LeftForeArm.transform.Find( "Left_Wrist_Joint_01" ).gameObject;
        RightShoulder = 
            Spine.transform.Find( "Right_Shoulder_Joint_01" ).gameObject;
        RightArm = 
            RightShoulder.transform.Find( "Right_Upper_Arm_Joint_01" ).gameObject;
        RightForeArm = 
            RightArm.transform.Find( "Right_Forearm_Joint_01" ).gameObject;
        RightHand = 
            RightForeArm.transform.Find( "Right_Wrist_Joint_01" ).gameObject;
        Hips = 
            Ref.gameObject.transform.Find( "Hip" ).gameObject;
        LeftUpLeg = 
            Hips.transform.Find( "Left_Thigh_Joint_01" ).gameObject;
        LeftLeg = 
            LeftUpLeg.transform.Find( "Left_Knee_Joint_01" ).gameObject;
        LeftAnkle = 
            LeftLeg.transform.Find( "Left_Ankle_Joint_01" ).gameObject;
        LeftToe = 
            LeftAnkle.transform.Find( "Left_Toe_Joint_01" ).gameObject;
        RightUpLeg = 
            Hips.transform.Find( "Right_Thigh_Joint_01" ).gameObject;
        RightLeg = 
            RightUpLeg.transform.Find( "Right_Knee_Joint_01" ).gameObject;
        RightAnkle = 
            RightLeg.transform.Find( "Right_Ankle_Joint_01" ).gameObject;
        RightToe = 
            RightAnkle.transform.Find( "Right_Toe_Joint_01" ).gameObject;

        FloorRB = Floor.GetComponent<Rigidbody>();
        RefRB = Ref.GetComponent<Rigidbody>();
        SpineRB = Spine.GetComponent<Rigidbody>();
        NeckRB = Neck.GetComponent<Rigidbody>();
        HeadRB = Head.GetComponent<Rigidbody>();
        LeftShoulderRB = LeftShoulder.GetComponent<Rigidbody>();
        LeftArmRB = LeftArm.GetComponent<Rigidbody>();
        LeftForeArmRB = LeftForeArm.GetComponent<Rigidbody>();
        LeftHandRB = LeftHand.GetComponent<Rigidbody>();
        RightShoulderRB = RightShoulder.GetComponent<Rigidbody>();
        RightArmRB = RightArm.GetComponent<Rigidbody>();
        RightForeArmRB = RightForeArm.GetComponent<Rigidbody>();
        RightHandRB = RightHand.GetComponent<Rigidbody>();
        HipsRB = Hips.GetComponent<Rigidbody>();
        LeftUpLegRB = LeftUpLeg.GetComponent<Rigidbody>();
        LeftLegRB = LeftLeg.GetComponent<Rigidbody>();
        LeftAnkleRB = LeftAnkle.GetComponent<Rigidbody>();
        LeftToeRB = LeftToe.GetComponent<Rigidbody>();
        RightUpLegRB = RightUpLeg.GetComponent<Rigidbody>();
        RightLegRB = RightLeg.GetComponent<Rigidbody>();
        RightAnkleRB = RightAnkle.GetComponent<Rigidbody>();
        RightToeRB = RightToe.GetComponent<Rigidbody>();

        Reward = 0;
        done = 0;
        Step = 0;
        target = 0;
        
        multiplier = 1000.0f;
        countdown = 10;
        initial_flag = true;
    }

    void FixedUpdate()
    {
        /*
        angle_x1 = Arm1.transform.localEulerAngles.x;
        if (180f < angle_x1 && angle_x1 < 360f)
        {
            angle_x1 = angle_x1 - 360f;
        }
        anguVelo_x1 = Arm1RB.angularVelocity.x;
        if (1.0f < anguVelo_x1){ anguVelo_x1 = 1.0f;}
        else if  ( anguVelo_x1 < -1.0f){ anguVelo_x1 = -1.0f;}
        angle_x2 = Arm2.transform.localEulerAngles.x;
        if (180f < angle_x2 && angle_x2 < 360f)
        {
            angle_x2 = angle_x2 - 360f;
        }
        anguVelo_x2 = Arm2RB.angularVelocity.x;
        if (1.0f < anguVelo_x2){ anguVelo_x2 = 1.0f;}
        else if  ( anguVelo_x2 < -1.0f){ anguVelo_x2 = -1.0f;}
        */

        GetStates();
        StatesSetDataOut();
        if (initial_flag)
        {
            data_Out.CopyTo(initStates, 0);
            initial_flag = false;
        }
        vectorAction = ServerRequest(data_Out);
        
        // Spine.transform.localEulerAngles += new Vector3(vectorAction[0], 0, 0);
        // Hips.transform.localEulerAngles += new Vector3(0, 0, vectorAction[1]);
        // LeftUpLeg.transform.localEulerAngles += new Vector3(0, 0, vectorAction[2]*multiplier);
        // LeftLeg.transform.localEulerAngles += new Vector3(0, 0, vectorAction[3]*multiplier);
        // LeftAnkle.transform.localEulerAngles += new Vector3(0, 0, vectorAction[4]*multiplier);
        // LeftToe.transform.localEulerAngles += new Vector3(vectorAction[5]*multiplier, 0, 0);
        // RightUpLeg.transform.localEulerAngles += new Vector3(0, 0, vectorAction[6]*multiplier);
        // RightLeg.transform.localEulerAngles += new Vector3(0, 0, vectorAction[7]*multiplier);
        // RightAnkle.transform.localEulerAngles += new Vector3(0, 0, vectorAction[8]*multiplier);
        // RightToe.transform.localEulerAngles += new Vector3(0, 0, vectorAction[9]*multiplier);

        SpineRB.AddTorque(new Vector3(vectorAction[0], 0, vectorAction[1]));
        HipsRB.AddTorque(new Vector3(0, vectorAction[2], 0));
        LeftUpLegRB.AddTorque(new Vector3(vectorAction[3]*multiplier, 0, 0));
        LeftLegRB.AddTorque(new Vector3(vectorAction[4]*multiplier, 0, 0));
        LeftAnkleRB.AddTorque(new Vector3(vectorAction[5]*multiplier, 0, 0));
        LeftToeRB.AddTorque(new Vector3(vectorAction[6]*multiplier, 0, 0));
        RightUpLegRB.AddTorque(new Vector3(vectorAction[7]*multiplier, 0, 0));
        RightLegRB.AddTorque(new Vector3(vectorAction[8]*multiplier, 0, 0));
        RightAnkleRB.AddTorque(new Vector3(vectorAction[9]*multiplier, 0, 0));
        RightToeRB.AddTorque(new Vector3(vectorAction[10]*multiplier, 0, 0));
   
        if ((countdown <= 0) || (stop_flag)) //achieve the goal
        {
            done = 9;
            Quit();
        }
        else if (Step+1 >= 1024*1024)
        {
            Reward = 0;
            done = 1;
            //countdown -= 1;
            target = 0;
            Reset();
        }
        else if (Ref_y < -1f)
        {
            Reward = 0;
            done = 1;
            Reset();
        }
        else if (Ref_z < target - 0.05)
        {
            Reward = 1;
            if (Ref_x < 0.1f && Ref_x > -0.1f)
            {
                Reward += 1;
            }
            Step += 1;
            target = Ref_z;
        }
        else
        {
            Reward = 0;
            Step += 1;
        } 
    }

    void Reset()
    {
        GetStates();
        StatesSetDataOut();
        vectorAction = ServerRequest(data_Out);
        SetInitStates();
        Reward = 0;
        done = 0;
        Step = 0;
        target = 0;
    }

    void Quit() 
    {
        data_Out[253] = done;
        ServerRequest(data_Out);

        #if UNITY_EDITOR
        EditorApplication.isPlaying = false;
        #elif UNITY_STANDALONE
        Application.Quit();
        #endif
    }

    void GetStates()
    {
        Ref_x = Ref.transform.position.x;
        Spine_x = Spine.transform.localPosition.x;
        Neck_x = Neck.transform.localPosition.x;
        Head_x = Head.transform.localPosition.x;
        LeftShoulder_x = LeftShoulder.transform.localPosition.x;
        LeftArm_x = LeftArm.transform.localPosition.x;
        LeftForeArm_x = LeftForeArm.transform.localPosition.x;
        LeftHand_x = LeftHand.transform.localPosition.x;
        RightShoulder_x = RightShoulder.transform.localPosition.x;
        RightArm_x = RightArm.transform.localPosition.x;
        RightForeArm_x = RightForeArm.transform.localPosition.x;
        RightHand_x = RightHand.transform.localPosition.x;       
        Hips_x = Hips.transform.localPosition.x;
        LeftUpLeg_x = LeftUpLeg.transform.localPosition.x;
        LeftLeg_x = LeftLeg.transform.localPosition.x;
        LeftAnkle_x = LeftAnkle.transform.localPosition.x;
        LeftToe_x = LeftToe.transform.localPosition.x;
        RightUpLeg_x = RightUpLeg.transform.localPosition.x;
        RightLeg_x = RightLeg.transform.localPosition.x;
        RightAnkle_x = RightAnkle.transform.localPosition.x;
        RightToe_x = RightToe.transform.localPosition.x;
        Ref_rx = Ref.transform.eulerAngles.x;
        Spine_rx = Spine.transform.localEulerAngles.x;
        Neck_rx = Neck.transform.localEulerAngles.x;
        Head_rx = Head.transform.localEulerAngles.x;
        LeftShoulder_rx = LeftShoulder.transform.localEulerAngles.x;
        LeftArm_rx = LeftArm.transform.localEulerAngles.x;
        LeftForeArm_rx = LeftForeArm.transform.localEulerAngles.x;
        LeftHand_rx = LeftHand.transform.localEulerAngles.x;
        RightShoulder_rx = RightShoulder.transform.localEulerAngles.x;
        RightArm_rx = RightArm.transform.localEulerAngles.x;
        RightForeArm_rx = RightForeArm.transform.localEulerAngles.x;
        RightHand_rx = RightHand.transform.localEulerAngles.x;
        Hips_rx = Hips.transform.localEulerAngles.x;
        LeftUpLeg_rx = LeftUpLeg.transform.localEulerAngles.x;
        LeftLeg_rx = LeftLeg.transform.localEulerAngles.x;
        LeftAnkle_rx = LeftAnkle.transform.localEulerAngles.x;
        LeftToe_rx = LeftToe.transform.localEulerAngles.x;
        RightUpLeg_rx = RightUpLeg.transform.localEulerAngles.x;
        RightLeg_rx = RightLeg.transform.localEulerAngles.x;
        RightAnkle_rx = RightAnkle.transform.localEulerAngles.x;
        RightToe_rx = RightToe.transform.localEulerAngles.x;
        Ref_y = Ref.transform.position.y;
        Spine_y = Spine.transform.localPosition.y;
        Neck_y = Neck.transform.localPosition.y;
        Head_y = Head.transform.localPosition.y;
        LeftShoulder_y = LeftShoulder.transform.localPosition.y;
        LeftArm_y = LeftArm.transform.localPosition.y;
        LeftForeArm_y = LeftForeArm.transform.localPosition.y;
        LeftHand_y = LeftHand.transform.localPosition.y;
        RightShoulder_y = RightShoulder.transform.localPosition.y;
        RightArm_y = RightArm.transform.localPosition.y;
        RightForeArm_y = RightForeArm.transform.localPosition.y;
        RightHand_y = RightHand.transform.localPosition.y;
        Hips_y = Hips.transform.localPosition.y;
        LeftUpLeg_y = LeftUpLeg.transform.localPosition.y;
        LeftLeg_y = LeftLeg.transform.localPosition.y;
        LeftAnkle_y = LeftAnkle.transform.localPosition.y;
        LeftToe_y = LeftToe.transform.localPosition.y;
        RightUpLeg_y = RightUpLeg.transform.localPosition.y;
        RightLeg_y = RightLeg.transform.localPosition.y;
        RightAnkle_y = RightAnkle.transform.localPosition.y;
        RightToe_y = RightToe.transform.localPosition.y;
        Ref_ry = Ref.transform.eulerAngles.y;
        Spine_ry = Spine.transform.localEulerAngles.y;
        Neck_ry = Neck.transform.localEulerAngles.y;
        Head_ry = Head.transform.localEulerAngles.y;
        LeftShoulder_ry = LeftShoulder.transform.localEulerAngles.y;
        LeftArm_ry = LeftArm.transform.localEulerAngles.y;
        LeftForeArm_ry = LeftForeArm.transform.localEulerAngles.y;
        LeftHand_ry = LeftHand.transform.localEulerAngles.y;
        RightShoulder_ry = RightShoulder.transform.localEulerAngles.y;
        RightArm_ry = RightArm.transform.localEulerAngles.y;
        RightForeArm_ry = RightForeArm.transform.localEulerAngles.y;
        RightHand_ry = RightHand.transform.localEulerAngles.y;
        Hips_ry = Hips.transform.localEulerAngles.y;
        LeftUpLeg_ry = LeftUpLeg.transform.localEulerAngles.y;
        LeftLeg_ry = LeftLeg.transform.localEulerAngles.y;
        LeftAnkle_ry = LeftAnkle.transform.localEulerAngles.y;
        LeftToe_ry = LeftToe.transform.localEulerAngles.y;
        RightUpLeg_ry = RightUpLeg.transform.localEulerAngles.y;
        RightLeg_ry = RightLeg.transform.localEulerAngles.y;
        RightAnkle_ry = RightAnkle.transform.localEulerAngles.y;
        RightToe_ry = RightToe.transform.localEulerAngles.y;
        Ref_z = Ref.transform.position.z;
        Spine_z = Spine.transform.localPosition.z;
        Neck_z = Neck.transform.localPosition.z;
        Head_z = Head.transform.localPosition.z;
        LeftShoulder_z = LeftShoulder.transform.localPosition.z;
        LeftArm_z = LeftArm.transform.localPosition.z;
        LeftForeArm_z = LeftForeArm.transform.localPosition.z;
        LeftHand_z = LeftHand.transform.localPosition.z;
        RightShoulder_z = RightShoulder.transform.localPosition.z;
        RightArm_z = RightArm.transform.localPosition.z;
        RightForeArm_z = RightForeArm.transform.localPosition.z;
        RightHand_z = RightHand.transform.localPosition.z;
        Hips_z = Hips.transform.localPosition.z;
        LeftUpLeg_z = LeftUpLeg.transform.localPosition.z;
        LeftLeg_z = LeftLeg.transform.localPosition.z;
        LeftAnkle_z = LeftAnkle.transform.localPosition.z;
        LeftToe_z = LeftToe.transform.localPosition.z;
        RightUpLeg_z = RightUpLeg.transform.localPosition.z;
        RightLeg_z = RightLeg.transform.localPosition.z;
        RightAnkle_z = RightAnkle.transform.localPosition.z;
        RightToe_z = RightToe.transform.localPosition.z;
        Ref_rz = Ref.transform.eulerAngles.z;
        Spine_rz = Spine.transform.localEulerAngles.z;
        Neck_rz = Neck.transform.localEulerAngles.z;
        Head_rz = Head.transform.localEulerAngles.z;
        LeftShoulder_rz = LeftShoulder.transform.localEulerAngles.z;
        LeftArm_rz = LeftArm.transform.localEulerAngles.z;
        LeftForeArm_rz = LeftForeArm.transform.localEulerAngles.z;
        LeftHand_rz = LeftHand.transform.localEulerAngles.z;
        RightShoulder_rz = RightShoulder.transform.localEulerAngles.z;
        RightArm_rz = RightArm.transform.localEulerAngles.z;
        RightForeArm_rz = RightForeArm.transform.localEulerAngles.z;
        RightHand_rz = RightHand.transform.localEulerAngles.z;
        Hips_rz = Hips.transform.localEulerAngles.z;
        LeftUpLeg_rz = LeftUpLeg.transform.localEulerAngles.z;
        LeftLeg_rz = LeftLeg.transform.localEulerAngles.z;
        LeftAnkle_rz = LeftAnkle.transform.localEulerAngles.z;
        LeftToe_rz = LeftToe.transform.localEulerAngles.z;
        RightUpLeg_rz = RightUpLeg.transform.localEulerAngles.z;
        RightLeg_rz = RightLeg.transform.localEulerAngles.z;
        RightAnkle_rz = RightAnkle.transform.localEulerAngles.z;
        RightToe_rz = RightToe.transform.localEulerAngles.z;
        RefRB_x = RefRB.velocity.x;
        SpineRB_x = SpineRB.velocity.x;
        NeckRB_x = NeckRB.velocity.x;
        HeadRB_x = HeadRB.velocity.x;
        LeftShoulderRB_x = LeftShoulderRB.velocity.x;
        LeftArmRB_x = LeftArmRB.velocity.x;
        LeftForeArmRB_x = LeftForeArmRB.velocity.x;
        LeftHandRB_x = LeftHandRB.velocity.x;
        RightShoulderRB_x = RightShoulderRB.velocity.x;
        RightArmRB_x = RightArmRB.velocity.x;
        RightForeArmRB_x = RightForeArmRB.velocity.x;
        RightHandRB_x = RightHandRB.velocity.x;
        HipsRB_x = HipsRB.velocity.x;
        LeftUpLegRB_x = LeftUpLegRB.velocity.x;
        LeftLegRB_x = LeftLegRB.velocity.x;
        LeftAnkleRB_x = LeftAnkleRB.velocity.x;
        LeftToeRB_x = LeftToeRB.velocity.x;
        RightUpLegRB_x = RightUpLegRB.velocity.x;
        RightLegRB_x = RightLegRB.velocity.x;
        RightAnkleRB_x = RightAnkleRB.velocity.x;
        RightToeRB_x = RightToeRB.velocity.x;
        RefRB_rx = RefRB.angularVelocity.x;
        SpineRB_rx = SpineRB.angularVelocity.x;
        NeckRB_rx = NeckRB.angularVelocity.x;
        HeadRB_rx = HeadRB.angularVelocity.x;
        LeftShoulderRB_rx = LeftShoulderRB.angularVelocity.x;
        LeftArmRB_rx = LeftArmRB.angularVelocity.x;
        LeftForeArmRB_rx = LeftForeArmRB.angularVelocity.x;
        LeftHandRB_rx = LeftHandRB.angularVelocity.x;
        RightShoulderRB_rx = RightShoulderRB.angularVelocity.x;
        RightArmRB_rx = RightArmRB.angularVelocity.x;
        RightForeArmRB_rx = RightForeArmRB.angularVelocity.x;
        RightHandRB_rx = RightHandRB.angularVelocity.x;
        HipsRB_rx = HipsRB.angularVelocity.x;
        LeftUpLegRB_rx = LeftUpLegRB.angularVelocity.x;
        LeftLegRB_rx = LeftLegRB.angularVelocity.x;
        LeftAnkleRB_rx = LeftAnkleRB.angularVelocity.x;
        LeftToeRB_rx = LeftToeRB.angularVelocity.x;
        RightUpLegRB_rx = RightUpLegRB.angularVelocity.x;
        RightLegRB_rx = RightLegRB.angularVelocity.x;
        RightAnkleRB_rx = RightAnkleRB.angularVelocity.x;
        RightToeRB_rx = RightToeRB.angularVelocity.x;
        RefRB_y = RefRB.velocity.y;
        SpineRB_y = SpineRB.velocity.y;
        NeckRB_y = NeckRB.velocity.y;
        HeadRB_y = HeadRB.velocity.y;
        LeftShoulderRB_y = LeftShoulderRB.velocity.y;
        LeftArmRB_y = LeftArmRB.velocity.y;
        LeftForeArmRB_y = LeftForeArmRB.velocity.y;
        LeftHandRB_y = LeftHandRB.velocity.y;
        RightShoulderRB_y = RightShoulderRB.velocity.y;
        RightArmRB_y = RightArmRB.velocity.y;
        RightForeArmRB_y = RightForeArmRB.velocity.y;
        RightHandRB_y = RightHandRB.velocity.y;
        HipsRB_y = HipsRB.velocity.y;
        LeftUpLegRB_y = LeftUpLegRB.velocity.y;
        LeftLegRB_y = LeftLegRB.velocity.y;
        LeftAnkleRB_y = LeftAnkleRB.velocity.y;
        LeftToeRB_y = LeftToeRB.velocity.y;
        RightUpLegRB_y = RightUpLegRB.velocity.y;
        RightLegRB_y = RightLegRB.velocity.y;
        RightAnkleRB_y = RightAnkleRB.velocity.y;
        RightToeRB_y = RightToeRB.velocity.y;
        RefRB_ry = RefRB.angularVelocity.y;
        SpineRB_ry = SpineRB.angularVelocity.y;
        NeckRB_ry = NeckRB.angularVelocity.y;
        HeadRB_ry = HeadRB.angularVelocity.y;
        LeftShoulderRB_ry = LeftShoulderRB.angularVelocity.y;
        LeftArmRB_ry = LeftArmRB.angularVelocity.y;
        LeftForeArmRB_ry = LeftForeArmRB.angularVelocity.y;
        LeftHandRB_ry = LeftHandRB.angularVelocity.y;
        RightShoulderRB_ry = RightShoulderRB.angularVelocity.y;
        RightArmRB_ry = RightArmRB.angularVelocity.y;
        RightForeArmRB_ry = RightForeArmRB.angularVelocity.y;
        RightHandRB_ry = RightHandRB.angularVelocity.y;
        HipsRB_ry = HipsRB.angularVelocity.y;
        LeftUpLegRB_ry = LeftUpLegRB.angularVelocity.y;
        LeftLegRB_ry = LeftLegRB.angularVelocity.y;
        LeftAnkleRB_ry = LeftAnkleRB.angularVelocity.y;
        LeftToeRB_ry = LeftToeRB.angularVelocity.y;
        RightUpLegRB_ry = RightUpLegRB.angularVelocity.y;
        RightLegRB_ry = RightLegRB.angularVelocity.y;
        RightAnkleRB_ry = RightAnkleRB.angularVelocity.y;
        RightToeRB_ry = RightToeRB.angularVelocity.y;
        RefRB_z = RefRB.velocity.z;
        SpineRB_z = SpineRB.velocity.z;
        NeckRB_z = NeckRB.velocity.z;
        HeadRB_z = HeadRB.velocity.z;
        LeftShoulderRB_z = LeftShoulderRB.velocity.z;
        LeftArmRB_z = LeftArmRB.velocity.z;
        LeftForeArmRB_z = LeftForeArmRB.velocity.z;
        LeftHandRB_z = LeftHandRB.velocity.z;
        RightShoulderRB_z = RightShoulderRB.velocity.z;
        RightArmRB_z = RightArmRB.velocity.z;
        RightForeArmRB_z = RightForeArmRB.velocity.z;
        RightHandRB_z = RightHandRB.velocity.z;
        HipsRB_z = HipsRB.velocity.z;
        LeftUpLegRB_z = LeftUpLegRB.velocity.z;
        LeftLegRB_z = LeftLegRB.velocity.z;
        LeftAnkleRB_z = LeftAnkleRB.velocity.z;
        LeftToeRB_z = LeftToeRB.velocity.z;
        RightUpLegRB_z = RightUpLegRB.velocity.z;
        RightLegRB_z = RightLegRB.velocity.z;
        RightAnkleRB_z = RightAnkleRB.velocity.z;
        RightToeRB_z = RightToeRB.velocity.z;
        RefRB_rz = RefRB.angularVelocity.z;
        SpineRB_rz = SpineRB.angularVelocity.z;
        NeckRB_rz = NeckRB.angularVelocity.z;
        HeadRB_rz = HeadRB.angularVelocity.z;
        LeftShoulderRB_rz = LeftShoulderRB.angularVelocity.z;
        LeftArmRB_rz = LeftArmRB.angularVelocity.z;
        LeftForeArmRB_rz = LeftForeArmRB.angularVelocity.z;
        LeftHandRB_rz = LeftHandRB.angularVelocity.z;
        RightShoulderRB_rz = RightShoulderRB.angularVelocity.z;
        RightArmRB_rz = RightArmRB.angularVelocity.z;
        RightForeArmRB_rz = RightForeArmRB.angularVelocity.z;
        RightHandRB_rz = RightHandRB.angularVelocity.z;
        HipsRB_rz = HipsRB.angularVelocity.z;
        LeftUpLegRB_rz = LeftUpLegRB.angularVelocity.z;
        LeftLegRB_rz = LeftLegRB.angularVelocity.z;
        LeftAnkleRB_rz = LeftAnkleRB.angularVelocity.z;
        LeftToeRB_rz = LeftToeRB.angularVelocity.z;
        RightUpLegRB_rz = RightUpLegRB.angularVelocity.z;
        RightLegRB_rz = RightLegRB.angularVelocity.z;
        RightAnkleRB_rz = RightAnkleRB.angularVelocity.z;
        RightToeRB_rz = RightToeRB.angularVelocity.z;
    }
    void StatesSetDataOut()
    {
        i = 0;
        data_Out[i] = Neck_x;
        i += 1;
        data_Out[i] = Head_x;
        i += 1;
        data_Out[i] = LeftShoulder_x;
        i += 1;
        data_Out[i] = LeftArm_x;
        i += 1;
        data_Out[i] = LeftForeArm_x;
        i += 1;
        data_Out[i] = LeftHand_x;
        i += 1;
        data_Out[i] = RightShoulder_x;
        i += 1;
        data_Out[i] = RightArm_x;
        i += 1;
        data_Out[i] = RightForeArm_x;
        i += 1;
        data_Out[i] = RightHand_x;
        i += 1;
        data_Out[i] = Neck_rx;
        i += 1;
        data_Out[i] = Head_rx;
        i += 1;
        data_Out[i] = LeftShoulder_rx;
        i += 1;
        data_Out[i] = LeftArm_rx;
        i += 1;
        data_Out[i] = LeftForeArm_rx;
        i += 1;
        data_Out[i] = LeftHand_rx;
        i += 1;
        data_Out[i] = RightShoulder_rx;
        i += 1;
        data_Out[i] = RightArm_rx;
        i += 1;
        data_Out[i] = RightForeArm_rx;
        i += 1;
        data_Out[i] = RightHand_rx;
        i += 1;
        data_Out[i] = Neck_y;
        i += 1;
        data_Out[i] = Head_y;
        i += 1;
        data_Out[i] = LeftShoulder_y;
        i += 1;
        data_Out[i] = LeftArm_y;
        i += 1;
        data_Out[i] = LeftForeArm_y;
        i += 1;
        data_Out[i] = LeftHand_y;
        i += 1;
        data_Out[i] = RightShoulder_y;
        i += 1;
        data_Out[i] = RightArm_y;
        i += 1;
        data_Out[i] = RightForeArm_y;
        i += 1;
        data_Out[i] = RightHand_y;
        i += 1;
        data_Out[i] = Neck_ry;
        i += 1;
        data_Out[i] = Head_ry;
        i += 1;
        data_Out[i] = LeftShoulder_ry;
        i += 1;
        data_Out[i] = LeftArm_ry;
        i += 1;
        data_Out[i] = LeftForeArm_ry;
        i += 1;
        data_Out[i] = LeftHand_ry;
        i += 1;
        data_Out[i] = RightShoulder_ry;
        i += 1;
        data_Out[i] = RightArm_ry;
        i += 1;
        data_Out[i] = RightForeArm_ry;
        i += 1;
        data_Out[i] = RightHand_ry;
        i += 1;
        data_Out[i] = Neck_z;
        i += 1;
        data_Out[i] = Head_z;
        i += 1;
        data_Out[i] = LeftShoulder_z;
        i += 1;
        data_Out[i] = LeftArm_z;
        i += 1;
        data_Out[i] = LeftForeArm_z;
        i += 1;
        data_Out[i] = LeftHand_z;
        i += 1;
        data_Out[i] = RightShoulder_z;
        i += 1;
        data_Out[i] = RightArm_z;
        i += 1;
        data_Out[i] = RightForeArm_z;
        i += 1;
        data_Out[i] = RightHand_z;
        i += 1;
        data_Out[i] = Neck_rz;
        i += 1;
        data_Out[i] = Head_rz;
        i += 1;
        data_Out[i] = LeftShoulder_rz;
        i += 1;
        data_Out[i] = LeftArm_rz;
        i += 1;
        data_Out[i] = LeftForeArm_rz;
        i += 1;
        data_Out[i] = LeftHand_rz;
        i += 1;
        data_Out[i] = RightShoulder_rz;
        i += 1;
        data_Out[i] = RightArm_rz;
        i += 1;
        data_Out[i] = RightForeArm_rz;
        i += 1;
        data_Out[i] = RightHand_rz;
        i += 1;
        data_Out[i] = NeckRB_x;
        i += 1;
        data_Out[i] = HeadRB_x;
        i += 1;
        data_Out[i] = LeftShoulderRB_x;
        i += 1;
        data_Out[i] = LeftArmRB_x;
        i += 1;
        data_Out[i] = LeftForeArmRB_x;
        i += 1;
        data_Out[i] = LeftHandRB_x;
        i += 1;
        data_Out[i] = RightShoulderRB_x;
        i += 1;
        data_Out[i] = RightArmRB_x;
        i += 1;
        data_Out[i] = RightForeArmRB_x;
        i += 1;
        data_Out[i] = RightHandRB_x;
        i += 1;
        data_Out[i] = NeckRB_rx;
        i += 1;
        data_Out[i] = HeadRB_rx;
        i += 1;
        data_Out[i] = LeftShoulderRB_rx;
        i += 1;
        data_Out[i] = LeftArmRB_rx;
        i += 1;
        data_Out[i] = LeftForeArmRB_rx;
        i += 1;
        data_Out[i] = LeftHandRB_rx;
        i += 1;
        data_Out[i] = RightShoulderRB_rx;
        i += 1;
        data_Out[i] = RightArmRB_rx;
        i += 1;
        data_Out[i] = RightForeArmRB_rx;
        i += 1;
        data_Out[i] = RightHandRB_rx;
        i += 1;
        data_Out[i] = NeckRB_y;
        i += 1;
        data_Out[i] = HeadRB_y;
        i += 1;
        data_Out[i] = LeftShoulderRB_y;
        i += 1;
        data_Out[i] = LeftArmRB_y;
        i += 1;
        data_Out[i] = LeftForeArmRB_y;
        i += 1;
        data_Out[i] = LeftHandRB_y;
        i += 1;
        data_Out[i] = RightShoulderRB_y;
        i += 1;
        data_Out[i] = RightArmRB_y;
        i += 1;
        data_Out[i] = RightForeArmRB_y;
        i += 1;
        data_Out[i] = RightHandRB_y;
        i += 1;
        data_Out[i] = NeckRB_ry;
        i += 1;
        data_Out[i] = HeadRB_ry;
        i += 1;
        data_Out[i] = LeftShoulderRB_ry;
        i += 1;
        data_Out[i] = LeftArmRB_ry;
        i += 1;
        data_Out[i] = LeftForeArmRB_ry;
        i += 1;
        data_Out[i] = LeftHandRB_ry;
        i += 1;
        data_Out[i] = RightShoulderRB_ry;
        i += 1;
        data_Out[i] = RightArmRB_ry;
        i += 1;
        data_Out[i] = RightForeArmRB_ry;
        i += 1;
        data_Out[i] = RightHandRB_ry;
        i += 1;
        data_Out[i] = NeckRB_z;
        i += 1;
        data_Out[i] = HeadRB_z;
        i += 1;
        data_Out[i] = LeftShoulderRB_z;
        i += 1;
        data_Out[i] = LeftArmRB_z;
        i += 1;
        data_Out[i] = LeftForeArmRB_z;
        i += 1;
        data_Out[i] = LeftHandRB_z;
        i += 1;
        data_Out[i] = RightShoulderRB_z;
        i += 1;
        data_Out[i] = RightArmRB_z;
        i += 1;
        data_Out[i] = RightForeArmRB_z;
        i += 1;
        data_Out[i] = RightHandRB_z;
        i += 1;
        data_Out[i] = NeckRB_rz;
        i += 1;
        data_Out[i] = HeadRB_rz;
        i += 1;
        data_Out[i] = LeftShoulderRB_rz;
        i += 1;
        data_Out[i] = LeftArmRB_rz;
        i += 1;
        data_Out[i] = LeftForeArmRB_rz;
        i += 1;
        data_Out[i] = LeftHandRB_rz;
        i += 1;
        data_Out[i] = RightShoulderRB_rz;
        i += 1;
        data_Out[i] = RightArmRB_rz;
        i += 1;
        data_Out[i] = RightForeArmRB_rz;
        i += 1;
        data_Out[i] = RightHandRB_rz;
        i += 1;
        data_Out[i] = Ref_x;
        i += 1;
        data_Out[i] = Spine_x;
        i += 1;
        data_Out[i] = Hips_x;
        i += 1;
        data_Out[i] = LeftUpLeg_x;
        i += 1;
        data_Out[i] = LeftLeg_x;
        i += 1;
        data_Out[i] = LeftAnkle_x;
        i += 1;
        data_Out[i] = LeftToe_x;
        i += 1;
        data_Out[i] = RightUpLeg_x;
        i += 1;
        data_Out[i] = RightLeg_x;
        i += 1;
        data_Out[i] = RightAnkle_x;
        i += 1;
        data_Out[i] = RightToe_x;
        i += 1;
        data_Out[i] = Ref_rx / 180f;
        i += 1;
        data_Out[i] = Spine_rx / 180f;
        i += 1;
        data_Out[i] = Hips_rx / 180f;
        i += 1;
        data_Out[i] = LeftUpLeg_rx / 180f;
        i += 1;
        data_Out[i] = LeftLeg_rx / 180f;
        i += 1;
        data_Out[i] = LeftAnkle_rx / 180f;
        i += 1;
        data_Out[i] = LeftToe_rx / 180f;
        i += 1;
        data_Out[i] = RightUpLeg_rx / 180f;
        i += 1;
        data_Out[i] = RightLeg_rx / 180f;
        i += 1;
        data_Out[i] = RightAnkle_rx / 180f;
        i += 1;
        data_Out[i] = RightToe_rx / 180f;
        i += 1;
        data_Out[i] = Ref_y;
        i += 1;
        data_Out[i] = Spine_y;
        i += 1;
        data_Out[i] = Hips_y;
        i += 1;
        data_Out[i] = LeftUpLeg_y;
        i += 1;
        data_Out[i] = LeftLeg_y;
        i += 1;
        data_Out[i] = LeftAnkle_y;
        i += 1;
        data_Out[i] = LeftToe_y;
        i += 1;
        data_Out[i] = RightUpLeg_y;
        i += 1;
        data_Out[i] = RightLeg_y;
        i += 1;
        data_Out[i] = RightAnkle_y;
        i += 1;
        data_Out[i] = RightToe_y;
        i += 1;
        data_Out[i] = Ref_ry / 180f;
        i += 1;
        data_Out[i] = Spine_ry / 180f;
        i += 1;
        data_Out[i] = Hips_ry / 180f;
        i += 1;
        data_Out[i] = LeftUpLeg_ry / 180f;
        i += 1;
        data_Out[i] = LeftLeg_ry / 180f;
        i += 1;
        data_Out[i] = LeftAnkle_ry / 180f;
        i += 1;
        data_Out[i] = LeftToe_ry / 180f;
        i += 1;
        data_Out[i] = RightUpLeg_ry / 180f;
        i += 1;
        data_Out[i] = RightLeg_ry / 180f;
        i += 1;
        data_Out[i] = RightAnkle_ry / 180f;
        i += 1;
        data_Out[i] = RightToe_ry / 180f;
        i += 1;
        data_Out[i] = Ref_z;
        i += 1;
        data_Out[i] = Spine_z;
        i += 1;
        data_Out[i] = Hips_z;
        i += 1;
        data_Out[i] = LeftUpLeg_z;
        i += 1;
        data_Out[i] = LeftLeg_z;
        i += 1;
        data_Out[i] = LeftAnkle_z;
        i += 1;
        data_Out[i] = LeftToe_z;
        i += 1;
        data_Out[i] = RightUpLeg_z;
        i += 1;
        data_Out[i] = RightLeg_z;
        i += 1;
        data_Out[i] = RightAnkle_z;
        i += 1;
        data_Out[i] = RightToe_z;
        i += 1;
        data_Out[i] = Ref_rz / 180f;
        i += 1;
        data_Out[i] = Spine_rz / 180f;
        i += 1;
        data_Out[i] = Hips_rz / 180f;
        i += 1;
        data_Out[i] = LeftUpLeg_rz / 180f;
        i += 1;
        data_Out[i] = LeftLeg_rz / 180f;
        i += 1;
        data_Out[i] = LeftAnkle_rz / 180f;
        i += 1;
        data_Out[i] = LeftToe_rz / 180f;
        i += 1;
        data_Out[i] = RightUpLeg_rz / 180f;
        i += 1;
        data_Out[i] = RightLeg_rz / 180f;
        i += 1;
        data_Out[i] = RightAnkle_rz / 180f;
        i += 1;
        data_Out[i] = RightToe_rz / 180f;
        i += 1;
        data_Out[i] = RefRB_x;
        i += 1;
        data_Out[i] = SpineRB_x;
        i += 1;
        data_Out[i] = HipsRB_x;
        i += 1;
        data_Out[i] = LeftUpLegRB_x;
        i += 1;
        data_Out[i] = LeftLegRB_x;
        i += 1;
        data_Out[i] = LeftAnkleRB_x;
        i += 1;
        data_Out[i] = LeftToeRB_x;
        i += 1;
        data_Out[i] = RightUpLegRB_x;
        i += 1;
        data_Out[i] = RightLegRB_x;
        i += 1;
        data_Out[i] = RightAnkleRB_x;
        i += 1;
        data_Out[i] = RightToeRB_x;
        i += 1;
        data_Out[i] = RefRB_rx;
        i += 1;
        data_Out[i] = SpineRB_rx;
        i += 1;
        data_Out[i] = HipsRB_rx;
        i += 1;
        data_Out[i] = LeftUpLegRB_rx;
        i += 1;
        data_Out[i] = LeftLegRB_rx;
        i += 1;
        data_Out[i] = LeftAnkleRB_rx;
        i += 1;
        data_Out[i] = LeftToeRB_rx;
        i += 1;
        data_Out[i] = RightUpLegRB_rx;
        i += 1;
        data_Out[i] = RightLegRB_rx;
        i += 1;
        data_Out[i] = RightAnkleRB_rx;
        i += 1;
        data_Out[i] = RightToeRB_rx;
        i += 1;
        data_Out[i] = RefRB_y;
        i += 1;
        data_Out[i] = SpineRB_y;
        i += 1;
        data_Out[i] = HipsRB_y;
        i += 1;
        data_Out[i] = LeftUpLegRB_y;
        i += 1;
        data_Out[i] = LeftLegRB_y;
        i += 1;
        data_Out[i] = LeftAnkleRB_y;
        i += 1;
        data_Out[i] = LeftToeRB_y;
        i += 1;
        data_Out[i] = RightUpLegRB_y;
        i += 1;
        data_Out[i] = RightLegRB_y;
        i += 1;
        data_Out[i] = RightAnkleRB_y;
        i += 1;
        data_Out[i] = RightToeRB_y;
        i += 1;
        data_Out[i] = RefRB_ry;
        i += 1;
        data_Out[i] = SpineRB_ry;
        i += 1;
        data_Out[i] = HipsRB_ry;
        i += 1;
        data_Out[i] = LeftUpLegRB_ry;
        i += 1;
        data_Out[i] = LeftLegRB_ry;
        i += 1;
        data_Out[i] = LeftAnkleRB_ry;
        i += 1;
        data_Out[i] = LeftToeRB_ry;
        i += 1;
        data_Out[i] = RightUpLegRB_ry;
        i += 1;
        data_Out[i] = RightLegRB_ry;
        i += 1;
        data_Out[i] = RightAnkleRB_ry;
        i += 1;
        data_Out[i] = RightToeRB_ry;
        i += 1;
        data_Out[i] = RefRB_z;
        i += 1;
        data_Out[i] = SpineRB_z;
        i += 1;
        data_Out[i] = HipsRB_z;
        i += 1;
        data_Out[i] = LeftUpLegRB_z;
        i += 1;
        data_Out[i] = LeftLegRB_z;
        i += 1;
        data_Out[i] = LeftAnkleRB_z;
        i += 1;
        data_Out[i] = LeftToeRB_z;
        i += 1;
        data_Out[i] = RightUpLegRB_z;
        i += 1;
        data_Out[i] = RightLegRB_z;
        i += 1;
        data_Out[i] = RightAnkleRB_z;
        i += 1;
        data_Out[i] = RightToeRB_z;
        i += 1;
        data_Out[i] = RefRB_rz;
        i += 1;
        data_Out[i] = SpineRB_rz;
        i += 1;
        data_Out[i] = HipsRB_rz;
        i += 1;
        data_Out[i] = LeftUpLegRB_rz;
        i += 1;
        data_Out[i] = LeftLegRB_rz;
        i += 1;
        data_Out[i] = LeftAnkleRB_rz;
        i += 1;
        data_Out[i] = LeftToeRB_rz;
        i += 1;
        data_Out[i] = RightUpLegRB_rz;
        i += 1;
        data_Out[i] = RightLegRB_rz;
        i += 1;
        data_Out[i] = RightAnkleRB_rz;
        i += 1;
        data_Out[i] = RightToeRB_rz;
        i += 1;
        data_Out[i] = Reward;
        i += 1;
        data_Out[i] = done;
    }
    void SetInitStates()
    {
        i = 0;
        Neck.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        Head.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftShoulder.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftArm.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftForeArm.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftHand.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightShoulder.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightArm.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightForeArm.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightHand.transform.localPosition = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        Neck.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        Head.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftShoulder.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftArm.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftForeArm.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        LeftHand.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightShoulder.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightArm.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightForeArm.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);
        i += 1;
        RightHand.transform.localEulerAngles = new Vector3(initStates[i], initStates[i+20], initStates[i+40]);

        i = 0;
        NeckRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        HeadRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftShoulderRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftArmRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftForeArmRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftHandRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightShoulderRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightArmRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightForeArmRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightHandRB.velocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        NeckRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        HeadRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftShoulderRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftArmRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftForeArmRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        LeftHandRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightShoulderRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightArmRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightForeArmRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);
        i += 1;
        RightHandRB.angularVelocity = new Vector3(initStates[i+60], initStates[i+80], initStates[i+100]);

        i = 0;
        Ref.transform.position = new Vector3(0f, 0f, 0f);
        i += 1;
        Spine.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        Hips.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        LeftUpLeg.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        LeftLeg.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        LeftAnkle.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        LeftToe.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        RightUpLeg.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        RightLeg.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        RightAnkle.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        RightToe.transform.localPosition = new Vector3(initStates[i+120], initStates[i+142], initStates[i+164]);
        i += 1;
        Ref.transform.eulerAngles = new Vector3(0f, 90f, -85f);
        i += 1;
        Spine.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        Hips.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        LeftUpLeg.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        LeftLeg.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        LeftAnkle.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        LeftToe.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        RightUpLeg.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        RightLeg.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        RightAnkle.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);
        i += 1;
        RightToe.transform.localEulerAngles = new Vector3(initStates[i+120] * 180f, initStates[i+142] * 180f, initStates[i+164] * 180f);

        i = 0;
        RefRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        SpineRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        HipsRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftUpLegRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftLegRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftAnkleRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftToeRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightUpLegRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightLegRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightAnkleRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightToeRB.velocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RefRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        SpineRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        HipsRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftUpLegRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftLegRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftAnkleRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        LeftToeRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightUpLegRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightLegRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightAnkleRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);
        i += 1;
        RightToeRB.angularVelocity = new Vector3(initStates[i+186], initStates[i+208], initStates[i+230]);

        Floor.transform.position = new Vector3(0f, -1.57f, 0f);
        Floor.transform.eulerAngles = new Vector3(0f, 0f, 0f);
        FloorRB.velocity = new Vector3(0f, 0f, 0f);
        FloorRB.angularVelocity = new Vector3(0f, 0f, 0f);
    }
}